{
 "title": "Switches Bandwidth",
 "tags": [ "Switches" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(rx_bytes,cluster)" } },
   {
    "name": "switch_hostname",
    "label": "Switch Hostname",
    "query": {
     "query": "label_values(rx_bytes{cluster=\"$cluster\"},switch_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Switches RX", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switches RX Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(rx_bytes{cluster='$cluster',switch_hostname=~'$switch_hostname'}[$__rate_interval]) * 8",
     "legendFormat": "{{port}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches RX Bandwidth Usage - % ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (8 * rate(rx_bytes{cluster=\"$cluster\", switch_hostname=~\"$switch_hostname\"}[$__rate_interval])\n/\non(cluster, switch_hostname, port)\ngroup_left\nlabel_replace(\n  nvswitch_interface_oper_aggregate_speed{cluster=\"$cluster\", switch_hostname=~\"$switch_hostname\"},\n  \"port\", \"$1\", \"interface\", \"(.*)\"\n))",
     "legendFormat": "{{switch_hostname}}, {{port}}"
    }
   ]
  },
  { "title": "Switches TX", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Switches TX Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tx_bytes{cluster='$cluster',switch_hostname=~'$switch_hostname'}[$__rate_interval]) * 8",
     "legendFormat": "{{port}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches TX Bandwidth Usage - % ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (8 * rate(tx_bytes{cluster=\"$cluster\", switch_hostname=~\"$switch_hostname\"}[$__rate_interval])\n/\non(cluster, switch_hostname, port)\ngroup_left\nlabel_replace(\n  nvswitch_interface_oper_aggregate_speed{cluster=\"$cluster\", switch_hostname=~\"$switch_hostname\"},\n  \"port\", \"$1\", \"interface\", \"(.*)\"\n))",
     "legendFormat": "{{switch_hostname}}, {{port}}"
    }
   ]
  }
 ]
}