{
 "title": "Capacity  Utilization",
 "tags": [ "Performance" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logical Capacity",
   "type": "stat",
   "description": "Note that the statistics here are based on current DRR, and may change accordingly.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Logical Space "
    },
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used "
    },
    {
     "expr": "100 * vast_cluster_logical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\"} - vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Remaining"
    }
   ]
  },
  {
   "title": "Capacity over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used "
    },
    {
     "expr": "100 * vast_cluster_logical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Logical Space "
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used"
    },
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Physical Space"
    },
    {
     "expr": "rate(vast_cluster_metrics_RaidMetrics_stripe_available_percent_sum{cluster='$cluster'}[$__rate_interval]) / rate(vast_cluster_metrics_RaidMetrics_stripe_available_percent_count{cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "Stripe Availability - Percentage"
    },
    {
     "expr": "100 * (sum(vast_quota_used_capacity{cluster=\"$cluster\"})/ sum(vast_quota_hard_limit{cluster=\"$cluster\"}))",
     "legendFormat": "Total Quota Usage - Percentage"
    },
    {
     "expr": "vast_cluster_metrics_Capacity_snapshots_count{cluster=\"$cluster\"}",
     "legendFormat": "Total Snapshots Count"
    },
    {
     "expr": "vast_cluster_metrics_Capacity_logical_inodes_in_use_num{cluster=\"$cluster\"}",
     "legendFormat": "Total Inodes Used"
    },
    {
     "expr": "vast_cluster_metrics_Capacity_used_handles_count{cluster=\"$cluster\"}",
     "legendFormat": "Total Handles Used"
    },
    {
     "expr": "vast_cluster_metrics_Capacity_used_handles_percent{cluster=\"$cluster\"}",
     "legendFormat": "Used Handles - Percentage"
    }
   ]
  },
  {
   "title": "Physical Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Physical Space "
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used "
    },
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"} - vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Remaining"
    }
   ]
  },
  {
   "title": "Last DRR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_drr{cluster=\"$cluster\"}",
     "legendFormat": "Data Reduction Ratio"
    }
   ]
  },
  {
   "title": "Auxiliary Capacity Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Space Used"
    },
    {
     "expr": "100 * vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"} / vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Used / Physical Used"
    },
    {
     "expr": "100 * vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"} /vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Used / Total Physical Space"
    }
   ]
  },
  {
   "title": "Quotas utilization",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_quota_used_capacity{cluster=\"$cluster\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "100 * vast_quota_used_capacity{cluster=\"$cluster\"} / vast_quota_hard_limit{cluster=\"$cluster\"} unless (vast_quota_hard_limit{cluster=\"$cluster\"} == 0)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "100 * vast_quota_used_inodes{cluster=\"$cluster\"} / vast_quota_hard_limit_inodes{cluster=\"$cluster\"} unless (vast_quota_hard_limit_inodes{cluster=\"$cluster\"} == 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vast_quota_used_inodes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}