{
 "title": "Switches State",
 "tags": [ "Switches" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nvswitch_interface_oper_state\t,cluster)"
    }
   },
   {
    "name": "hostname",
    "label": "Switch Hostname",
    "query": {
     "query": "label_values(nvswitch_interface_oper_state\t{cluster=\"$cluster\"},switch_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Switches State",
   "type": "table",
   "description": "Switch ports configured with a route, that are currently inactive.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "switch_reachable{cluster='$cluster', switch_hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NTP Servers Unreachable ",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "ntp_server_reachable{cluster=\"$cluster\", switch_hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Ports Unreachable",
   "type": "table",
   "description": "Switch ports configured with a route, that are currently inactive.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "nvswitch_interface_oper_state{cluster=\"$cluster\", switch_hostname=~\"$hostname\"} != 1\nAND on(cluster, interface, switch_hostname)\nnvswitch_interface_flags{cluster=\"$cluster\", switch_hostname=~\"$hostname\"} % 2 == 1",
     "legendFormat": "{{switch_ip}}"
    }
   ]
  },
  {
   "title": "Missing VTEPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "missing_vtep{cluster='$cluster', switch_hostname=~\"$hostname\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing BGP Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "bgp_connection_missing{cluster='$cluster', switch_hostname=~\"$hostname\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switches Roce No Buffer Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_pg_rx_buffer_discard{switch_hostname=~\"$hostname\", pg=\"3\", cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "{{interface}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches Roce General Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_sp_rx_discard{switch_hostname=~\"$hostname\", sp=\"3\", cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "{{interface}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches BER Effective Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_phy_stats_phy_effective_errors{switch_hostname=~'$hostname', cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "{{interface}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Buffer Usage Percentage - TC 0 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (nvswitch_shared_buffer_pool_curr_occupancy{cluster='$cluster', switch_hostname=~\"$hostname\", pool_id='2'} / nvswitch_shared_buffer_pool_watermark{cluster='$cluster', switch_hostname=~\"$hostname\", pool_id='2'})",
     "legendFormat": "{{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Buffer Usage Percentage - TC 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (nvswitch_shared_buffer_pool_curr_occupancy{cluster='$cluster', switch_hostname=~\"$hostname\", pool_id='3'} / nvswitch_shared_buffer_pool_watermark{cluster='$cluster', switch_hostname=~\"$hostname\", pool_id='3'})",
     "legendFormat": "{{switch_hostname}}"
    }
   ]
  },
  {
   "title": "ARP Packets Violations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "rate(switch_arp_violations{cluster=\"$cluster\", switch_hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches RX Paused Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_sp_rx_pause{switch_hostname=~'$hostname', sp=\"3\", cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "{{interface}}, {{switch_hostname}}"
    }
   ]
  },
  {
   "title": "Switches TX Paused Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_sp_tx_pause{switch_hostname=~'$hostname', sp=\"3\", cluster='$cluster'}[$__rate_interval])",
     "legendFormat": "{{interface}}, {{switch_hostname}}"
    }
   ]
  }
 ]
}