{
 "title": "DNodes, SSDs and NVRAMs",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNodes Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_dnode_metrics_Hardware_mem_percent{cluster=\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "DBox Power Consumptiom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "vast_psu_metrics_Hardware_total_power{cluster=\"$cluster\", title=~\".*dbox.*\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "DNode CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_dnode_metrics_Hardware_cpu_temp{cluster=\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "SSD / NVRAM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_temperature{cluster=\"$cluster\"} OR vast_ssd_metrics_Hardware_temperature{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "SSD Endurance over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_ssd_metrics_Hardware_endurance{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "NVRAM Endurance over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_endurance{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cluster Physical Capacity Used - %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Read Latency per NVRAM Device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_r_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Write Latency per NVRAM Device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_w_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Read Latency per SSD device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_ssd_metrics_Hardware_r_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Write Latency per SSD device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_ssd_metrics_Hardware_w_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  }
 ]
}