{
 "title": "Replication Streams",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_drr,cluster)"
    }
   },
   {
    "name": "cluster_ip",
    "query": {
     "query": "label_values(vast_cluster_drr{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(vast_replication_stream_bw{cluster=\"$cluster\"},source_tenant_name)"
    }
   },
   {
    "name": "rep_stream",
    "label": "Replication Stream",
    "query": {
     "query": "label_values(vast_replication_stream_bw{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replication Logical Backlog",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vast_replication_stream_logical_backlog{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Stream Physical Backlog",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vast_replication_stream_physical_backlog{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Stream BW",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vast_replication_stream_bw{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Stream Logical Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vast_replication_stream_logical_size{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RPO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vast_replication_stream_rpo{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RPO Offset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vast_replication_stream_rpo_offset{cluster=\"$cluster\", source_tenant_name=~\"$tenant\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}