{
 "title": "Top Actors - Views",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   { "name": "k", "label": "Amount of Views to Display", "query": "2, 5, 10, 50, 100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p><br></p>\n<h1 style=\"text-align: center;\">Per View Performance Metrics - Top N</h1>\n<p style=\"text-align: center;\">Please note that the exact number of views shown here is dependant on the chosen time range. <br>\nFor a larger time range, there might be shown more views than the chosen number, since there's a higher chance that the most active views were changed over time.\n</p>"
   }
  },
  {
   "title": "Average Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_read_bw_sum{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_write_bw_sum{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_read_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_view_metrics_ViewMetrics_read_latency_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_write_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_view_metrics_ViewMetrics_write_latency_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_read_iops_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_write_iops_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read Metadata IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_read_md_iops_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Write Metadata IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_write_md_iops_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}