{
 "title": "Kafka Cluster Metrics",
 "tags": [ "Performance" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fetch Event IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_fetch_event_iops{cluster=\"$cluster\"}",
     "legendFormat": "Fetch Event IOPS"
    }
   ]
  },
  {
   "title": "Produce Event IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_produce_event_iops{cluster=\"$cluster\"}",
     "legendFormat": "Produce Event IOPS"
    }
   ]
  },
  {
   "title": "Fetch Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_fetch_bw{cluster=\"$cluster\"}",
     "legendFormat": "Fetch BW"
    }
   ]
  },
  {
   "title": "Produce Bandwitdh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_produce_bw{cluster=\"$cluster\"}",
     "legendFormat": "Produce BW"
    }
   ]
  },
  {
   "title": "Fetch Message Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_fetch_msg_latency{cluster=\"$cluster\"}",
     "legendFormat": "Fetch Message Latency"
    }
   ]
  },
  {
   "title": "Produce Message Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_KafkaProtoMetrics_produce_msg_latency{cluster=\"$cluster\"}",
     "legendFormat": "Produce Message Latency"
    }
   ]
  }
 ]
}