{
 "title": "Kafka Targets",
 "tags": [ "Performance" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Broker - Events Published (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(vast_kafka_broker_metrics_kafka_external_events_published{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Kafka Broker - Events Returned an Error (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(vast_kafka_broker_metrics_kafka_external_events_returned_an_error{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Kafka Broker - Events Total Failures (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(vast_kafka_broker_metrics_kafka_external_events_failures_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Kafka Broker - Events Failed to Send (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(vast_kafka_broker_metrics_kafka_external_events_failed_to_send{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}