{
 "title": "Protocols Metadata Statistics",
 "tags": [ "Performance" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NFSv3 Metadata Action Count (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mkdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mknod"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "symlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rmdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rename"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "link"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdirplus"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsstat"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "pathconf"
    }
   ]
  },
  {
   "title": "NFSv4 Metadata Action Count (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_setattr_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getattr_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_stateid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "free_stateid"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_secinfo_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "secinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookupp_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookupp"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookup_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_commit_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_close_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "close"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_savefh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "savefh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_readdir_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_session_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create_session"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_session_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "destroy_session"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_access_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_sequence_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "sequence"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_remove_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_exchange_id_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "exchange_id"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_clientid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "destroy_clientid"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_open_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "open"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putpubfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putpubfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putrootfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putrootfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_reclaim_complete_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "reclaim_complete"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_restorefh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "restorefh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_secinfo_no_name_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "secinfo_no_name"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_test_stateid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "test_stateid"
    }
   ]
  },
  {
   "title": "S3 Metadata Action Count (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetService"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucketLocation"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "HeadBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteObject"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteObjects"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "HeadObject"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutBucketAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucketAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutObjecttAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetObjectAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutObjectCopy"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "CreateMultipartUpload"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "CompleteMultipartUpload"
    }
   ]
  },
  {
   "title": "NFSv3 Metadata Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_create_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_mkdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mkdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_mknod_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "mknod"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_symlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "symlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_setattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_remove_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_rmdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rmdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_rename_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "rename"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_link_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "link"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_commit_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_getattr_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_lookup_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_access_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readlink_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readlink"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readdir_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_readdirplus_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdirplus"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_fsstat_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsstat"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_fsinfo_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "fsinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_NfsMetrics_nfs_pathconf_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "pathconf"
    }
   ]
  },
  {
   "title": "NFSv4 Metadata Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_setattr_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_setattr_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "setattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getattr_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getattr_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getattr"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_stateid_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_stateid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "free_stateid"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_secinfo_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_free_secinfo_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "secinfo"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookupp_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookupp_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookupp"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookup_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_lookup_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_commit_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_commit_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_close_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_close_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "close"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_savefh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_savefh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "savefh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_readdir_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_readdir_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "readdir"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_session_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_session_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create_session"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_session_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_session_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "destroy_session"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_access_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_access_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "access"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_sequence_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_sequence_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "sequence"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_remove_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_remove_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_exchange_id_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_exchange_id_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "exchange_id"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_clientid_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_destroy_clientid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "destroy_clientid"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_create_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getfh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_getfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "getfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_open_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_open_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "open"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putfh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putpubfh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putpubfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putpubfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putrootfh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_putrootfh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "putrootfh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_reclaim_complete_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_reclaim_complete_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "reclaim_complete"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_restorefh_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_restorefh_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "restorefh"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_secinfo_no_name_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_secinfo_no_name_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "secinfo_no_name"
    },
    {
     "expr": "rate(vast_cluster_metrics_Nfs4Metrics_nfs4_test_stateid_req_latency_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_Nfs4Metrics_nfs4_test_stateid_req_latency_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "test_stateid"
    }
   ]
  },
  {
   "title": "S3 Metadata Average Latency",
   "type": "timeseries",
   "description": "These metrics are on a 5m interval. Internally VAST only updates these once every 5m.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_service_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_service_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetService"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_location_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_location_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucketLocation"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_head_bucket_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_head_bucket_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "HeadBucket"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_object_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteObject"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_delete_objects_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_delete_objects_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "DeleteObjects"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_head_object_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_head_object_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "HeadObject"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutBucketAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_bucket_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetBucketAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutObjecttAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_get_object_acl_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_get_object_acl_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GetObjectAcl"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_put_object_copy_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_put_object_copy_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "PutObjectCopy"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_initiate_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_initiate_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "CreateMultipartUpload"
    },
    {
     "expr": "rate(vast_cluster_metrics_S3Metrics_complete_mpu_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(vast_cluster_metrics_S3Metrics_complete_mpu_count{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "CompleteMultipartUpload"
    }
   ]
  },
  {
   "title": "NFSv3 Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{proto_name=\"NFSCommon\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_write_size_count{proto_name=\"NFSCommon\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Write"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{proto_name=\"NFSCommon\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_read_size_count{proto_name=\"NFSCommon\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Read"
    }
   ]
  },
  {
   "title": "NFSv4 Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{proto_name=\"NFS4Common\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_write_size_count{proto_name=\"NFS4Common\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Write"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{proto_name=\"NFS4Common\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_read_size_count{proto_name=\"NFS4Common\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Read"
    }
   ]
  },
  {
   "title": "S3 Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{proto_name=\"S3Common\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_write_size_count{proto_name=\"S3Common\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Write"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{proto_name=\"S3Common\", cluster=\"$cluster\"}[$__rate_interval])\n/\nrate(vast_cluster_metrics_ProtoMetrics_read_size_count{proto_name=\"S3Common\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": " Avg Request Size - Read"
    }
   ]
  }
 ]
}