{
 "title": "Top Actors - Views",
 "tags": [ "Performance" ],
 "time": { "from": "now-4h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   {
    "name": "view",
    "label": "Views",
    "query": {
     "query": "label_values(vast_view_logical_capacity{cluster=\"$cluster\"},path)"
    }
   },
   { "name": "k", "label": "Amount of Views to Display", "query": "2, 5, 10, 50, 100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p><br></p>\n<h1 style=\"text-align: center;\">Per View Performance and Capacity Metrics - Top N</h1>\n<p style=\"text-align: center;\">Wider time ranges may show more views than the chosen top-N, since the most active views can shift over time.\n</p>"
   }
  },
  {
   "title": "View Quota - Capacity",
   "type": "timeseries",
   "description": "All Selected Views",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vast_quota_used_capacity{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Used Capacity"
    },
    {
     "expr": "vast_quota_soft_limit{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Soft Limit"
    },
    {
     "expr": "vast_quota_hard_limit{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Hard Limit"
    }
   ]
  },
  {
   "title": "View Quota - Inodes",
   "type": "timeseries",
   "description": "All Selected Views",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "vast_quota_used_inodes{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Used Inodes"
    },
    {
     "expr": "vast_quota_soft_limit_inodes{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Soft Limit"
    },
    {
     "expr": "vast_quota_hard_limit_inodes{cluster=\"$cluster\", path=~\"$view\"}",
     "legendFormat": "{{path}} - Hard Limit"
    }
   ]
  },
  {
   "title": "View Logical Capacity",
   "type": "timeseries",
   "description": "Excluding \"/\" view",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, vast_view_logical_capacity{cluster=\"$cluster\", path!=\"/\", path=~\"$view\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "View Physical Capacity",
   "type": "timeseries",
   "description": "Excluding \"/\" view",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, vast_view_physical_capacity{cluster=\"$cluster\", path!=\"/\", path=~\"$view\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "QoS Average Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_view_metrics_ViewMetrics_qos_wait_for_budget_time_sum{cluster=\"$cluster\", path=~\"$view\"}[$__rate_interval]) / rate(vast_view_metrics_ViewMetrics_qos_wait_for_budget_time_count{cluster=\"$cluster\", path=~\"$view\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_read_bw{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_write_bw{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  (\n    sum by (path) (\n        vast_user_view_read_latency{cluster=\"$cluster\", path=~\"$view\"}\n      * on (cluster, username, uid, path, protocol, bucket, share, name, alias)\n        vast_user_view_read_iops{cluster=\"$cluster\", path=~\"$view\"}\n    )\n  /\n    sum by (path) (\n        vast_user_view_read_iops{cluster=\"$cluster\", path=~\"$view\"}\n    )\n  )\n  and\n  sum by (path) (\n    vast_user_view_read_iops{cluster=\"$cluster\", path=~\"$view\"}\n  ) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  (\n    sum by (path) (\n        vast_user_view_write_latency{cluster=\"$cluster\", path=~\"$view\"}\n      * on (cluster, username, uid, path, protocol, bucket, share, name, alias)\n        vast_user_view_write_iops{cluster=\"$cluster\", path=~\"$view\"}\n    )\n  /\n    sum by (path) (\n        vast_user_view_write_iops{cluster=\"$cluster\", path=~\"$view\"}\n    )\n  )\n  and\n  sum by (path) (\n    vast_user_view_write_iops{cluster=\"$cluster\", path=~\"$view\"}\n  ) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_read_iops{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_write_iops{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_read_md_iops{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Write Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\n  $k,\n  sum by (path) (\n    vast_user_view_write_md_iops{cluster=\"$cluster\", path=~\"$view\"}\n  )\n)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}