{
 "title": "Top Actors - Users + Views",
 "tags": [ "Performance" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_drr,cluster)"
    }
   },
   { "name": "k", "label": "Amount of Users to Display", "query": "2, 5, 10, 20, 50, 100" },
   {
    "name": "view",
    "label": "Views",
    "query": {
     "query": "label_values(vast_view_logical_capacity{cluster=\"$cluster\"},path)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p><br></p>\n<h1 style=\"text-align: center;\">Per User & View Performance Metrics - Top N</h1>"
   }
  },
  {
   "title": "Average Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_read_bw{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Average Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_write_bw{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_read_latency{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_write_latency{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Read Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_read_md_iops{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Write Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_write_md_iops{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_read_iops{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, vast_user_view_write_iops{cluster=\"$cluster\", path=~\"$view\"})",
     "legendFormat": "{{username}}, {{uid}}, {{path}}"
    }
   ]
  }
 ]
}