{
 "title": "NICs State",
 "tags": [ "Switches" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online{cluster!=\"VAIS24494900\"},cluster)"
    }
   },
   {
    "name": "cn",
    "label": "Node",
    "query": {
     "query": "label_values(vast_cnode_active{cluster=\"$cluster\", name=~\"$c\"},hostname)"
    }
   },
   {
    "name": "c",
    "label": "CNode Name",
    "query": {
     "query": "label_values(vast_cnode_active{cluster=\"$cluster\"},name)"
    }
   },
   {
    "name": "d",
    "label": "DNode name",
    "query": {
     "query": "label_values(vast_dnode_active{cluster=\"$cluster\"},name)"
    }
   },
   {
    "name": "dn",
    "query": {
     "query": "label_values(vast_dnode_active{cluster=\"$cluster\", name=~\"$d\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NICs Current State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vast_nic_active{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Node NICs State Changes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vast_nic_active{cluster='$cluster', hostname=~\"($cn|$dn)\"} - vast_nic_active{cluster='$cluster', hostname=~\"($cn|$dn)\"} offset 2m",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Node NIC Read BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "expr": "vast_nic_metrics_Hardware_r_mbs{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"} * 8 * 0.953674316",
     "legendFormat": " {{hostname}} - {{display_name}}"
    }
   ]
  },
  {
   "title": "Node NIC Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "expr": "vast_nic_metrics_Hardware_t_mbs{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"} * 8 * 0.953674316",
     "legendFormat": " {{hostname}}, {{display_name}}"
    }
   ]
  },
  {
   "title": "Out of Buffer Errors per NIC - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_out_of_buffer{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Out of Sequence Errors per NIC - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_out_of_sequence{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs Duplicate Requests - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_duplicate_request{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs RNR NAK Retry Errors - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_rnr_nak_retry_err{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs CRC Errors - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_rx_crc_errors_phy{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs Paused Packets - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_t_pause{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs Local Ack Timeout Errors - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_local_ack_timeout_err{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs Jittering Cables - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_jittering_cable{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{cable_serial_number}},{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Hardware Symbol Errors per Node NIC - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_rx_symbol_err_phy{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "NICs Buffer Allocation Errors - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_rx_buff_alloc_err{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Hardware TX Errors per Node NIC - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_tx_errors_phy{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "Hardware RX Invalid Packet Length Errors per Node NIC - per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(vast_nic_metrics_Hardware_rx_in_range_len_errors_phy{cluster=\"$cluster\", hostname=~\"($cn|$dn)\"}[$__rate_interval])",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  }
 ]
}