{
 "title": "CNodes",
 "tags": [ "VAST" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   {
    "name": "vippool",
    "label": "Vippool",
    "query": {
     "query": "label_values(vast_cnode_vippool{cluster=\"$cluster\"},vippool)"
    }
   },
   {
    "name": "cn",
    "label": "CNode",
    "query": {
     "query": "label_values(vast_cnode_vippool{vippool=~\"$vippool\", cluster=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "NFSv3 : NFSCommon, NFSv4 : NFS4Common, S3 : S3Common, SMB : SMBCommon"
   }
  ]
 },
 "panels": [
  {
   "title": "CNodes State",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vast_cnode_active{cluster=\"$cluster\", hostname=~\"$cn\"} unless (vast_cnode_failed{cluster=\"$cluster\", hostname=~\"$cn\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vast_cnode_failed{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans State",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "vast_fan_active{cluster=\"$cluster\", box=~\".*cbox.*\"}",
     "legendFormat": "{{title}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "CNode NICs State",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "vast_nic_active{cluster=\"$cluster\", hostname=~\".*cn.*\", hostname=~\"$cn\"}",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "CNodes State over Time",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "vast_cnode_active{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CNode CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_Hardware_cpu_temp{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CBox Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "vast_psu_metrics_Hardware_total_power{cluster=\"$cluster\", title=~\".*cbox.*\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "CNode Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_Hardware_mem_percent{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CNode CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(vast_cnode_metrics_SchedulerMetrics_window_runtime_sum{cluster=\"$cluster\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_SchedulerMetrics_window_runtime_count{cluster=\"$cluster\", hostname=~\"$cn\"}[$__rate_interval]) / 500000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CNode Read BW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{proto_name}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "CNode Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{proto_name}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Average Read Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\", proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "Average Write Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\", proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Read Metadata IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_ProtoMetrics_rd_md_iops{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write Metadata IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_ProtoMetrics_wr_md_iops{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  },
  {
   "title": "Active Connections per Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections per CNode - NFSv3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\", hostname=~\"$cn\"}",
       "legendFormat": "NFSv3 - {{hostname}}"
      }
     ]
    },
    {
     "title": "Active Connections per CNode - S3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 57 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\", hostname=~\"$cn\"} ",
       "legendFormat": "S3 - {{hostname}}"
      }
     ]
    },
    {
     "title": "Active Connections per CNode - NFSv4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_Nfs4Metrics_nfs4_open_connections_cnt{cluster=\"$cluster\", hostname=~\"$cn\"}",
       "legendFormat": "NFSv4 - {{hostname}}"
      }
     ]
    },
    {
     "title": "Active Connections per CNode - SMB",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
     "targets": [
      {
       "expr": "vast_cnode_metrics_ProtoConnectionMetrics_smb_conn_pool{cluster=\"$cluster\", hostname=~\"$cn\"}",
       "legendFormat": "SMB - {{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}