{
 "title": "DNodes",
 "tags": [ "VAST" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNodes State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vast_dnode_active{cluster=\"$cluster\"} unless (vast_dnode_failed{cluster=\"$cluster\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vast_dnode_failed{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSDs State",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "vast_ssd_active{cluster=\"$cluster\"} unless (vast_ssd_failed{cluster=\"$cluster\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vast_ssd_failed{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCMs State",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "vast_nvram_active{cluster=\"$cluster\"} unless (vast_nvram_failed{cluster=\"$cluster\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vast_nvram_failed{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans State",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 8 },
   "targets": [
    {
     "expr": "vast_fan_active{cluster=\"$cluster\", box=~\".*dbox.*\"}",
     "legendFormat": "{{title}}, {{hostname}}"
    }
   ]
  },
  {
   "title": "DNodes NICs State",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vast_nic_active{cluster=\"$cluster\", hostname=~\".*dn.*\"}",
     "legendFormat": "{{display_name}}, {{hostname}}"
    }
   ]
  },
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DNode CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_dnode_metrics_Hardware_cpu_temp{cluster=\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "SSD / NVRAM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_temperature{cluster=\"$cluster\"} OR vast_ssd_metrics_Hardware_temperature{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "DBox Power Consumptiom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "vast_psu_metrics_Hardware_total_power{cluster=\"$cluster\", title=~\".*dbox.*\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "DNodes Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_dnode_metrics_Hardware_mem_percent{cluster=\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Read Latency per SCM Device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_r_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Write Latency per SCM Device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_nvram_metrics_Hardware_w_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Read Latency per SSD device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_ssd_metrics_Hardware_r_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Write Latency per SSD device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vast_ssd_metrics_Hardware_w_await{cluster=\"$cluster\"}",
     "legendFormat": "{{title}}"
    }
   ]
  }
 ]
}