{
 "title": "Performance by User + Protocol",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_drr,cluster)"
    }
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "NFSv3 : NFS3, NFSv4 : NFS4, S3, SMB : SMB2"
   },
   {
    "name": "username",
    "label": "User",
    "query": {
     "query": "label_values(vast_user_view_latency{cluster=\"$cluster\"},username)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_read_bw{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Average Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_write_bw{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_read_latency{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_write_latency{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Read Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_read_md_iops{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Write Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_write_md_iops{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_read_iops{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(vast_user_view_write_iops{cluster=\"$cluster\", protocol=~\"$proto\", username=~\"$username\"}) by (username, protocol)",
     "legendFormat": "{{username}}, {{protocol}}"
    }
   ]
  }
 ]
}