{
 "title": "CNodes",
 "tags": [ "Performance" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   {
    "name": "vippool",
    "label": "Vippool",
    "query": {
     "query": "label_values(vast_cnode_vippool{cluster=\"$cluster\"},vippool)"
    }
   },
   {
    "name": "cn",
    "label": "CNode",
    "query": {
     "query": "label_values(vast_cnode_vippool{vippool=~\"$vippool\", cluster=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "NFSv3 : NFSCommon, NFSv4 : NFS4Common, S3 : S3Common, SMB : SMBCommon, Replication : ReplicationCommon"
   }
  ]
 },
 "panels": [
  {
   "title": "CNode Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_Hardware_mem_percent{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CNode CPU Utilization",
   "type": "timeseries",
   "description": "600K Is the upper threshold, however values higher than 400K indicate CNode overload.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " 100 * ((rate(vast_cnode_metrics_SchedulerMetrics_window_runtime_sum{cluster=\"$cluster\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_SchedulerMetrics_window_runtime_count{cluster=\"$cluster\", hostname=~\"$cn\"}[$__rate_interval]))) / 500000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CNode CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_Hardware_cpu_temp{cluster=\"$cluster\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CBox Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "vast_psu_metrics_Hardware_total_power{cluster=\"$cluster\", title=~\".*cbox.*\"}",
     "legendFormat": "{{title}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CNode Read BW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{proto_name}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "CNode Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{proto_name}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Average Read Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\", proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}} - {{proto_name}}"
    }
   ]
  },
  {
   "title": "Average Write Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\", proto_name=~\"$proto\", hostname=~\"$cn\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Read Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_ProtoMetrics_rd_md_iops{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  },
  {
   "title": "CNode Write Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cnode_metrics_ProtoMetrics_wr_md_iops{cluster=\"$cluster\",proto_name=~\"$proto\", hostname=~\"$cn\"}",
     "legendFormat": "{{hostname}}, {{proto_name}}"
    }
   ]
  }
 ]
}