{
 "title": "VAST Cluster Statistics - Main",
 "description": "Visualization VAST cluster metrics.",
 "tags": [ "VAST" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_drr,cluster)"
    }
   },
   {
    "name": "cluster_ip",
    "label": "Cluster IP",
    "query": {
     "query": "label_values(vast_cnode_active{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Components",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(id) (vast_cnode_failed{cluster=\"$cluster\"}))",
     "legendFormat": "CNodes"
    },
    {
     "expr": "count(count by(id) (vast_dnode_failed{cluster=\"$cluster\"}))",
     "legendFormat": "DNodes"
    },
    {
     "expr": "count(count by(title) (vast_ssd_failed{cluster=\"$cluster\"}))",
     "legendFormat": "SSDs"
    },
    {
     "expr": "count(count by(title) (vast_nvram_failed{cluster=\"$cluster\"}))",
     "legendFormat": "SCMs"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical"
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "SCM RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_nvram_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "NVRAM State"
    }
   ]
  },
  {
   "title": "Inactive NICs - CNodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vast_nic_active{cluster=\"$cluster\", hostname=~\".*cn.*\"}) - sum(vast_nic_active{cluster=\"$cluster\", hostname=~\".*cn.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarm Counter ",
   "type": "table",
   "description": "Click to see all alarms",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum(vast_vms_alarms{event_name!='NOTIFIER_EVENT', cluster='$cluster'}) by (severity, event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSD RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_ssd_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "SSD State"
    }
   ]
  },
  {
   "title": "Failed Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_cnode_failed{cluster=\"$cluster\"})",
     "legendFormat": "CNodes"
    },
    {
     "expr": "sum(vast_dnode_failed{cluster=\"$cluster\"})",
     "legendFormat": "DNodes"
    },
    {
     "expr": "sum(vast_ssd_failed{cluster=\"$cluster\"})",
     "legendFormat": "SSDs"
    },
    {
     "expr": "sum(vast_nvram_failed{cluster=\"$cluster\"})",
     "legendFormat": "SCMs"
    }
   ]
  },
  {
   "title": "Inactive Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_cnode_inactive{cluster=\"$cluster\"} AND vast_cnode_failed{cluster=\"$cluster\"} == 0)",
     "legendFormat": "CNodes"
    },
    {
     "expr": "sum(vast_dnode_inactive{cluster=\"$cluster\"} AND vast_dnode_failed{cluster=\"$cluster\"} == 0)",
     "legendFormat": "DNodes"
    },
    {
     "expr": "sum(vast_ssd_inactive{cluster=\"$cluster\"} AND vast_ssd_failed{cluster=\"$cluster\"} == 0)",
     "legendFormat": "SSDs"
    },
    {
     "expr": "sum(vast_nvram_inactive{cluster=\"$cluster\"} AND vast_nvram_failed{cluster=\"$cluster\"} == 0)",
     "legendFormat": "SCMs"
    }
   ]
  },
  {
   "title": "Physical Space usage - Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"} / vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space usage - Percentage"
    }
   ]
  },
  {
   "title": "Inactive NICs - DNodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vast_nic_active{cluster=\"$cluster\", hostname=~\".*dn.*\"}) - sum(vast_nic_active{cluster=\"$cluster\", hostname=~\".*dn.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_memory_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "Memory State"
    }
   ]
  },
  {
   "title": "Critical Alarms",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "vast_vms_alarms{cluster=\"$cluster\", severity=\"CRITICAL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_rd_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_wr_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average Bandwidth & Latency",
   "type": "timeseries",
   "description": "Note that there might be seen spikes that don't reflect reality after cluster reboot. ",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(vast_cnode_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]))",
     "legendFormat": "Read BW"
    },
    {
     "expr": "sum(rate(vast_cnode_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]))",
     "legendFormat": "Write BW"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Read + Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average Read Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Write Latency Per CNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(vast_cnode_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval]) / rate(vast_cnode_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}