{
 "title": "Multi Cluster Monitoring",
 "tags": [ "VAST" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Clusters Overview",
   "type": "table",
   "description": "The API of every cluster that appears here was accessible in the past 1s.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "vast_cluster_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Switches Unreachable",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "switch_reachable", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Switch Ports Unreachable",
   "type": "table",
   "description": "Switch ports configured with a route, that are currently inactive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "nvswitch_interface_oper_state != 1",
     "legendFormat": "{{switch_ip}}"
    }
   ]
  },
  {
   "title": "Failed SSDs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "vast_ssd_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed DNodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "vast_dnode_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed CNodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "vast_cnode_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed NVRAMs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "vast_nvram_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inactive Fans",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "vast_fan_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inactive NICs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "vast_nic_active", "legendFormat": "__auto" }
   ]
  }
 ]
}