{
 "title": "Performance by Vip / Vippool",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   {
    "name": "vippool",
    "label": "Vippool",
    "query": {
     "query": "label_values(vast_cnode_vippool{cluster=\"$cluster\"},vippool)"
    }
   },
   {
    "name": "vip",
    "label": "Vip",
    "query": {
     "query": "label_values(vast_vip_read_bw{cluster=\"$cluster\"},title)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Vippool Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read + Write IOPS per Vippool ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_vippool_read_iops{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Read"
    },
    {
     "expr": "vast_vippool_write_iops{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Write"
    }
   ]
  },
  {
   "title": "Bandwidth & Latency per Vippool ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "vast_vippool_read_bw{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Read BW"
    },
    {
     "expr": "vast_vippool_write_bw{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Write BW"
    },
    {
     "expr": "vast_vippool_read_latency{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Read Latency"
    },
    {
     "expr": "vast_vippool_write_latency{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Write Latency"
    }
   ]
  },
  {
   "title": "Read + Write MD IOPS per Vippool ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_vippool_read_md_iops{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Read"
    },
    {
     "expr": "vast_vippool_write_md_iops{cluster=\"$cluster\", title=~\"$vippool\"}",
     "legendFormat": "{{title}} - Write"
    }
   ]
  },
  { "title": "Per Vip Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read + Write IOPS per Vip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_vip_read_iops{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Read"
    },
    {
     "expr": "vast_vip_write_iops{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Write"
    }
   ]
  },
  {
   "title": "Bandwidth & Latency per Vip",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "vast_vip_read_bw{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Read BW"
    },
    {
     "expr": "vast_vip_write_bw{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Write BW"
    },
    {
     "expr": "vast_vip_read_latency{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Read Latency"
    },
    {
     "expr": "vast_vip_write_latency{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Write Latency"
    }
   ]
  },
  {
   "title": "Read + Write MD IOPS per Vip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_vip_read_md_iops{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Read"
    },
    {
     "expr": "vast_vip_write_md_iops{cluster=\"$cluster\", title=~\"$vip\"}",
     "legendFormat": "{{title}} - Write"
    }
   ]
  }
 ]
}