{
 "title": "Top Actors - Tenant",
 "tags": [ "Performance" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(vast_cluster_drr,cluster)"
    }
   },
   {
    "name": "cluster_ip",
    "query": {
     "query": "label_values(vast_cluster_drr{cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "k", "label": "Amount of Tenants to Display", "query": "2, 5, 10, 50, 100" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(vast_tenant_metrics_TenantMetrics_read_bw_avg{cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p><br></p>\n<h1 style=\"text-align: center;\">Per Tenant Performance Metrics - Top N</h1>\n<p style=\"text-align: center;\">Please note that the exact number of tenants shown here is dependant on the chosen time range. <br>\nFor a larger time range, there might be shown more tenants than the chosen number, since there's a higher chance that the most active tenants were changed over time.\n</p>"
   }
  },
  {
   "title": "Average Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_read_bw_sum{cluster=\"$cluster\", tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_write_bw_sum{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_read_latency_sum{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]) / rate(vast_tenant_metrics_TenantMetrics_read_latency_count{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($k, vast_tenant_metrics_TenantMetrics_write_latency_avg{cluster=\"$cluster\", name=~\"$tenant\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_read_iops_avg{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_write_iops_count{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_read_md_iops_count{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Write Metadata IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(vast_tenant_metrics_TenantMetrics_write_md_iops_avg{cluster=\"$cluster\", name=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}